version: '3.8'
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data
    ports:
      - '5432:5432'
  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/data
    depends_on:
      - db
    ports:
      - '3000:3000'
